import os
import xml.etree.ElementTree as ET
from utils import logging
from decouple import config
import lxml.html as html


class XMLUtil:
    "Main class for xml based scripts related to this challenge"

    __log = logging.Logger.get_instance()

    @classmethod
    def get_book_name_byfield(cls,file):
        book = {}
        root = ET.fromstring(file)
        author = []
        title = []
        year = []

        cls.__log.info('locate BOOK TITLE, YEAR and AUTHOR NAME element in xml')

        for node in root.findall(config('XPATH_TITLE')):
            # cls.log.info(node.text)
            title.append(node.text)

        for node in root.findall(config('XPATH_AUTHOR')):
            # cls.log.info(node.text)
            author.append(node.text)

        for node in root.findall(config('XPATH_YEAR')):
            if node.text is not None:
                year.append(node.text)
            else:
                year.append("")

        temp = {key: value for (key, value) in zip(author, year)}

        temp2 = {key: value for (key, value) in zip(author, title)}

        # print(temp.keys())
        # print(zip(temp.values(), temp2.values()))
        #
        # cls.book = { i:list(j) for i in temp.keys() for j in zip(temp.values(), temp2.values())}
        cls.__log.info('processing dictionaries generated by parsing xml')

        ds = [temp, temp2]

        for k in temp.keys():
            book[k] = tuple(d[k] for d in ds)

        return book


    @classmethod
    def get_book_name_byyear(cls, file):

        author = []
        title = []
        root = html.fromstring(file)

        cls.__log.info('locate BOOK TITLE and AUTHOR NAME element in html')

        for node in root.xpath(config('XPATH_YEAR_TITLE')):
            title.append(node.text_content())

        for node in root.xpath(config('XPATH_YEAR_AUTHOR')):
            author.append(node.text_content())

        book = {key: value for (key, value) in zip(author, title)}

        return book

    @classmethod
    def get_book_name_byquote(cls, file):

        author = []
        title = []
        root = html.fromstring(file)

        cls.__log.info('locate BOOK TITLE and AUTHOR NAME element in html')
        for node in root.xpath(config('XPATH_QUOTE_TITLE')):
            title.append(node.text_content())

        for node in root.xpath(config('XPATH_QUOTE_AUTHOR')):
            author.append(node.text_content())

        book = {key: value for (key, value) in zip(author, title)}

        return book






    """
        OLD METHOD NEED be commented out or removed, kept for reference.
    """
    def _get_book_name_byfield(cls,file):
        #tree = et.ElementTree(file=os.path.dirname(os.getcwd()) + "/ignore/" + "byfield.xml")
        cls.__log.info('in get_book method')

        with open (os.path.dirname(os.getcwd()) + "/ignore/" + "byfield.xml",'w+') as xml_file:
            xml_file.write(file)
        cls.__log.info('xml file created')

        tree = ET.parse(os.path.dirname(os.getcwd()) + "/ignore/" + "byfield.xml")

        cls.__log.info('tree object created')

        root = tree.getroot()

        cls.__log.info('root object created')

        book_elements = list(list(root)[1][6])

        cls.__log.info('Book element object created, location can be changed if xml changes')

        author = [(list(book_elements[i][8][2])[1]).text for i in range(0,len(book_elements))]
        title = [(book_elements[i][8][1]).text for i in range(0,len(book_elements))]
        cls.__log.info('Created author and title list')

        cls.__book = {key: value for (key, value) in zip(author, title)}

        return cls.__book

    """
        old method can be commented out or removed, kept for reference.
    """
    def _get_book_name_byyear(cls, file):

        cls.__log.info('in get_book_name_byyear method')
        with open(os.path.dirname(os.getcwd()) + "/ignore/" + "byyear.html", 'w+') as xml_file:
            xml_file.write(file)
        cls.__log.info('xml file created')

        tree = ET.parse(os.path.dirname(os.getcwd()) + "/ignore/" + "byyear.html")

        cls.__log.info('tree object created')
        root = tree.getroot()
        cls.__log.info(list(root))


